# Site settings
title: Remote Sensing
SEOTitle: 天空地一体化烟草智能感知
header-img: img/space-bg8.jpg
email: tuow1105@gmail.com
description: "Test1"
keyword: "Spatial,Remote Sensing,GIS,RS,Image Process"
url: "http://www.remotesensing.pro"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/giswt/remotesensing.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "WT"
sidebar-avatar: /img/myself1.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     giswt
zhihu_username:     wtgis
github_username:    giswt
#facebook_username:  baiying.qiu.7
jianshu_username:   giswt
#twitter_username:   giswt




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: giswt

# Gitalk
#gitalk:
  #enable: true    #是否开启Gitalk评论
  #clientID: baaa458f521ce3977cb4                            #生成的clientID
  #clientSecret: 8fbdae5e33d80226be165835a4f5e772670aa70b    #生成的clientSecret
  #repo: giswt.github.io    #仓库名称
  #owner: giswt    #github用户名
  #admin: giswt
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 9053ac4a405658283975aa19016a9666

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
     #   title: "WY",
    #    href: "http://zhengwuyang.com"
   # },{
    #    title: "简书·BY",
    #    href: "http://www.jianshu.com/u/e71990ada2fd"
   # },{
   #     title: "Apple",
   #     href: "https://apple.com"
   # },{
   #     title: "Apple Developer",
   #     href: "https://developer.apple.com/"
  #  }
#]
